[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/cosmetics-store-manager.html"
  status = 200

[[headers]]
  for = "/cosmetics-store-manager.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
